// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKC8511MGgxkEoKVsVPxdK8NUQ8z_iM1Y',
    appId: '1:1059412108912:web:1300dbb20cc6aff189b6b5',
    messagingSenderId: '1059412108912',
    projectId: 'pollutracker-bf276',
    authDomain: 'pollutracker-bf276.firebaseapp.com',
    storageBucket: 'pollutracker-bf276.firebasestorage.app',
    measurementId: 'G-3HHL2W240B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQmZlLwycS9KBIgovV_Sc9BL53t_jJfHM',
    appId: '1:1059412108912:android:602506d7018e058189b6b5',
    messagingSenderId: '1059412108912',
    projectId: 'pollutracker-bf276',
    storageBucket: 'pollutracker-bf276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIXfSoCy4X26q-HcL6K0dr7J474Dsfh5Y',
    appId: '1:1059412108912:ios:4ede96d41c91cef189b6b5',
    messagingSenderId: '1059412108912',
    projectId: 'pollutracker-bf276',
    storageBucket: 'pollutracker-bf276.firebasestorage.app',
    iosBundleId: 'com.example.pollutrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIXfSoCy4X26q-HcL6K0dr7J474Dsfh5Y',
    appId: '1:1059412108912:ios:4ede96d41c91cef189b6b5',
    messagingSenderId: '1059412108912',
    projectId: 'pollutracker-bf276',
    storageBucket: 'pollutracker-bf276.firebasestorage.app',
    iosBundleId: 'com.example.pollutrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKC8511MGgxkEoKVsVPxdK8NUQ8z_iM1Y',
    appId: '1:1059412108912:web:f8a9a82a7a93137589b6b5',
    messagingSenderId: '1059412108912',
    projectId: 'pollutracker-bf276',
    authDomain: 'pollutracker-bf276.firebaseapp.com',
    storageBucket: 'pollutracker-bf276.firebasestorage.app',
    measurementId: 'G-PMC7SC95TP',
  );
}
